# ai_model.py
import pandas as pd, numpy as np
from sklearn.linear_model import LinearRegression

def train_model(df): ...
def predict_future_cost(model,last_week,weeks_ahead): ...
def total_predicted_cost(df,model,weeks_ahead): ...
